#!/bin/sh

cd /home/orangepi/modbus_server
mix deps.get
mix compile
mix release
/home/orangepi/modbus_server/_build/dev/rel/modbus_server/bin/modbus_server restart

# git update-index --chmod=+x path/to/file